export const Currency = Object.freeze({
  BTC: 'BTC',
  DOGE: 'DOGE',
  ETH: 'ETH',
  LTC: 'LTC',
  DASH: 'DASH',
  BCH: 'BCH',
  XRP: 'XRP',
  TRX: 'TRX',
  XLM: 'XLM',
  BNB: 'BNB',
  USDT: 'USDT',
  USDC: 'USDC',
  ADA: 'ADA',
  EOS: 'EOS',
  SHIB: 'SHIB',
  TON: 'TON',
});

export const System = Object.freeze({
  BITCOIN: '11',
  ETHEREUM: '12',
  LITECOIN: '14',
  DOGECOIN: '15',
  DASH: '16',
  BITCOIN_CASH: '18',
  RIPPLE: '22',
  TRON: '27',
  STELLAR: '28',
  BINANCECOIN: '29',
  TRON_TRC20: '30',
  BINANCESMARTCHAIN_BEP20: '31',
  ETHEREUM_ERC20: '32',
  TON: '33',
});

export const TransactionPriority = Object.freeze({
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
});

export const PsCurList = [
  'bitcoin_btc',
  'ethereum_eth',
  'litecoin_ltc',
  'dogecoin_doge',
  'dash_dash',
  'bitcoincash_bch',
  'ripple_xrp',
  'tron_trx',
  'stellar_xlm',
  'binancecoin_bnb',
  'tron_trc20_usdt',
  'binancesmartchain_bep20_usdt',
  'ethereum_erc20_usdt',
  'binancesmartchain_bep20_usdc',
  'binancesmartchain_bep20_ada',
  'binancesmartchain_bep20_eos',
  'binancesmartchain_bep20_btc',
  'binancesmartchain_bep20_eth',
  'binancesmartchain_bep20_doge',
  'ton_ton',
  'ton_usdt',
];
